### PR TITLE
Some updates to Branches and Pull Requests fetching

### PR DESCRIPTION
**Pull request by michaeltokar**
Added the ability to pull 'metadata' (from plugins) into Branch mode; 
added UPDATED and REVIEWED pull request activity action types; 
fixed a bug when searching for pull requests by participant involvement

### CODE REVIEW

**Comment by cornelcreanga** [comment]
For health reason I will be unable to do too much work,  at least the following months.  Sorry for that.

**Comment by cornelcreanga** [comment]
you might want to clone the repository and do your own releases

**Comment by michaeltokar** [comment]
Hi @cornelcreanga ,

So given that I now have push access, would you still like me to merge this PR to your repository? I can maintain my own fork as well, but thought you could at least benefit from this too :)

BTW I am an Atlassian engineer, working on this in my spare time. I may be able to convince others to also use/improve the library you've developed. If you would prefer them work on my fork, that's fine too.

**Comment by cornelcreanga** [comment]
Hi,

As it suits you better, just please let me know what you'll decide. 

There are several 'must' improvements related to authentication, right now its a naive approach.

After I'll leave the hospital (3-4 months) I'll start again looking into it.

Cornel 

On Sunday, 13 November 2016, 5:21, michaeltokar notifications@github.com wrote:

Hi @cornelcreanga ,
So given that I now have push access, would you still like me to merge this PR to your repository? I can maintain my own fork as well, but thought you could at least benefit from this too :)
BTW I am an Atlassian engineer, working on this in my spare time. I may be able to convince others to also use/improve the library you've developed. If you would prefer them work on my fork, that's fine too.

**Pull request merged**
